analyzer_rules:
  - unused_import

trailing_comma:
    mandatory_comma: true

opt_in_rules:
  - implicit_return
  - let_var_whitespace
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - sorted_imports

file_length:
  warning: 1000
  error: 1600

type_body_length:
  warning: 780

function_body_length:
  warning: 60
  error: 80  
